[build]
  command = "yarn build"
  publish = ".next"
  
[[plugins]]
package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "https://bestpetlove.net/:splat"
  status = 301
  force = true
